# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'BUADVADemo_Swift.xcworkspace'

abstract_target 'Demo' do
    pod 'Google-Mobile-Ads-SDK','7.52.0'
    pod 'Ads-Global'

    target 'BUADVADemo_Swift' do
      project 'BUADVADemo_Swift.xcodeproj'

    end
    
end