use_frameworks!

target 'Bytedance_UnionAd_Example' do
  pod 'Bytedance-UnionAD', :path => '../'
  pod 'Google-Mobile-Ads-SDK'

  target 'Bytedance_UnionAd_Tests' do
    inherit! :search_paths

  end
end
