# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'BUADDemo.xcworkspace'

abstract_target 'Demo' do
    pod 'AFNetworking', '~> 3.0', :subspecs => ['UIKit'], :inhibit_warnings => false
    pod 'KVOController'
    pod 'Masonry'
    pod 'Google-Mobile-Ads-SDK','7.52.0'
    pod 'MBProgressHUD'
    pod 'libwebp', '~> 0.5.1'  
    pod 'Bugly'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Ads-CN-Beta'

    target 'BUADDemo' do
      project 'BUADDemo.xcodeproj'

    end
    
end

