# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'BUADVADemo.xcworkspace'

abstract_target 'Demo' do
    pod 'Google-Mobile-Ads-SDK'
    pod 'Bugly'
    pod 'SDWebImage'
    pod 'Ads-Global', '~> 4.6.2.2'
 

    target 'BUADVADemo' do
      project 'BUADVADemo.xcodeproj'

    end
    
end