# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PangleQuickStartDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # This is for SDK v3.4.x.x and later
  #pod 'Ads-Global','3.6.1.7'
  pod 'mopub-ios-sdk'

  pod 'MoPub-Pangle-Adapters', '3.6.1.7.0'
  pod 'Ads-Global','3.6.1.7',:subspecs => ['Domestic']

  # This is for SDK v3.3.6.2 and before
  # pod 'Bytedance-UnionAD'

  # Pods for PangleQuickStartDemo

  target 'PangleQuickStartDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PangleQuickStartDemoUITests' do
    # Pods for testing
  end

end
