# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'BUDemo.xcworkspace'

abstract_target 'Demo' do
    pod 'AFNetworking', '~> 3.0', :subspecs => ['UIKit'], :inhibit_warnings => false
    pod 'KVOController'
    pod 'Masonry'
    pod 'Google-Mobile-Ads-SDK','7.52.0'
    pod 'MBProgressHUD'
    pod 'libwebp', '~> 0.5.1'
    pod 'mopub-ios-sdk/Core','5.10.0'    
    pod 'Bugly'
    pod 'Fabric'
    pod 'Crashlytics'

    target 'BUADDemo' do
      project 'BUADDemo.xcodeproj'

    end
    
end

